/**
 * Validators for Driver API routes
 *
 * SECURITY NOTE: These are PUBLIC endpoints accessed via shareable tokens.
 * Validation is critical to prevent abuse.
 */

const { body, param } = require('express-validator');
const {
    handleValidationErrors,
    validateIntId,
    validateLatitude,
    validateLongitude,
    validateOptionalString,
    validateOptionalPositiveInt
} = require('./index');

/**
 * Validate driver token parameter
 * Tokens are 64-character hex strings generated by crypto.randomBytes(32)
 */
const validateDriverToken = param('token')
    .matches(/^[a-f0-9]{64}$/)
    .withMessage('Invalid token format');

/**
 * Validate route ID for authenticated share/token endpoints
 */
const validateRouteId = validateIntId('id');

/**
 * Validate order ID for driver operations
 */
const validateOrderId = validateIntId('orderId');

// ==================== ROUTE-SPECIFIC VALIDATORS ====================

/**
 * POST /api/delivery/route/:id/share
 * Generate shareable token for a route
 */
const shareRoute = [
    validateRouteId,
    validateOptionalPositiveInt('expiresInHours', { min: 1, max: 168 }), // Max 7 days
    handleValidationErrors
];

/**
 * GET /api/delivery/route/:id/token
 * Get active token for a route
 */
const getRouteToken = [
    validateRouteId,
    handleValidationErrors
];

/**
 * DELETE /api/delivery/route/:id/token
 * Revoke active token for a route
 */
const revokeRouteToken = [
    validateRouteId,
    handleValidationErrors
];

/**
 * GET /api/driver/:token
 * PUBLIC: Get route data for contract driver
 */
const getDriverRoute = [
    validateDriverToken,
    handleValidationErrors
];

/**
 * POST /api/driver/:token/orders/:orderId/complete
 * PUBLIC: Mark order as completed
 */
const completeOrder = [
    validateDriverToken,
    validateOrderId,
    handleValidationErrors
];

/**
 * POST /api/driver/:token/orders/:orderId/skip
 * PUBLIC: Skip an order
 */
const skipOrder = [
    validateDriverToken,
    validateOrderId,
    handleValidationErrors
];

/**
 * POST /api/driver/:token/orders/:orderId/pod
 * PUBLIC: Upload POD (proof of delivery) photo
 */
const uploadPod = [
    validateDriverToken,
    validateOrderId,
    validateLatitude('latitude'),
    validateLongitude('longitude'),
    handleValidationErrors
];

/**
 * POST /api/driver/:token/finish
 * PUBLIC: Finish route and retire token
 */
const finishRoute = [
    validateDriverToken,
    validateOptionalString('driverName', { maxLength: 100 }),
    validateOptionalString('driverNotes', { maxLength: 2000 }),
    handleValidationErrors
];

module.exports = {
    shareRoute,
    getRouteToken,
    revokeRouteToken,
    getDriverRoute,
    completeOrder,
    skipOrder,
    uploadPod,
    finishRoute
};
